###############################################################################
#                          Generated on liqiankun                             #
###############################################################################
version: "3.1"
services:
  nginx:
    image: ${NGINX_IMAGE_TAG}
    container_name: nginx
    working_dir: /var/www/html
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./www:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    ports:
       - "8082:8082"
      #  - "443:443"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - lnmp

  php-fpm:
    image: ${IMAGE_NAMESPACE}${PHP_IMAGE_TAG}
    container_name: php-fpm
    # user: "www-data"
    volumes:
      - ./www:/var/www/html
      - ./config/php/conf.d/over-php.ini:/usr/local/etc/php/conf.d/over-php.ini
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - lnmp

  redis:
    image: ${REDIS_IMAGE_TAG}
    container_name: redis
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"  
    networks:
      - lnmp

  mysql:
    image: ${IMAGE_NAMESPACE}${MYSQL_IMAGE_TAG}
    container_name: mysql8
    working_dir: /application
    command:
      # - --default-authentication-plugin=mysql_native_password
      # - --mysql-native-password=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql/${MYSQL_VERSION}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=liqiankun
      - MYSQL_USER=root2
      - MYSQL_PASSWORD=root2
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - lnmp
networks:
  lnmp:
    driver: bridge